version: '3'

services:
  api:
    image: node:19-alpine3.16
    volumes:
      - "./api:/app"
    depends_on:
      - redis
    working_dir: /app
    command: "npm run start"
  apitest:
    image: node:19-alpine3.16
    env_file: "api/.env"
    volumes:
      - "./api:/app"
    depends_on:
      - redis
    working_dir: /app
    command: "npm run test"
  client:
    image: node:19-alpine3.16
    volumes:
      - "./client:/app"
    working_dir: /app
    ports:
      - "3000:3000"
    command: "npm run start:dev"
  redis:
    image: "redis:alpine"
    #ports:
    #  - "6379:6379"
    volumes:
      - "./data/redis:/redis-data"
    command: ["redis-server", "--requirepass", "hy&T9PGFBYJBGA"]
